name: Generate Fabrication Outputs

on:
  push:
    branches:
      - dev

jobs:
  generate-fabrication-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            libgtk-3-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libwebkit2gtk-4.0-dev \
            libgstreamer1.0-dev \
            libcanberra-gtk3-dev \
            pkg-config \
            libglib2.0-dev \
            libwxgtk3.0-gtk3-dev \
            libnotify-dev \
            libsm-dev \
            libice-dev \
            libxtst-dev
            
      - name: Install wxPython using pip
        run: |
          python -m pip install --upgrade pip
          pip install wxPython

      - name: Verify wxPython installation
        run: |
          python -c "import wx; print(wx.__version__)"
        
      - name: Install KiCad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad

      - name: Clone Fabrication Toolkit
        run: |
          git clone https://github.com/bennymeg/Fabrication-Toolkit.git
          ls

      - name: Run fab toolkit CLI
        run: |
          cd Fabrication-Toolkit
          python3 -m plugins.cli -p ../KiCad/Rev_1_0/RP2040-Decoder.kicad_pcb
        
      - name: Archive Outputs
        run: |
          ls
          zip -r fabrication_outputs.zip fabrication_outputs
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabrication-outputs
          path: fabrication_outputs.zip
