name: pcb_image
on:
  push:
    branches:
      - dev   # Trigger on push to 'dev' branch
      - main  # Trigger on push to 'main' branch
    paths:
      - '.github/workflows/pcb_render.yml'  # Trigger if this workflow file changes
      - 'KiCad/**'  # Trigger if any file in the 'KiCad' directory changes

jobs:
  render-image:
    name: render-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Render PCB image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: KiCad/RP2040-Decoder.kicad_pcb
          output_path: ${{ github.workspace }}/images

      - name: Upload images as artifact
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v3
        with:
          name: pcb-images
          path: images/

  deploy-pages-main:
    if: github.ref == 'refs/heads/main'  # Only deploy on 'main' branch
    runs-on: ubuntu-latest
    needs: render-image

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or update gh-pages branch (main)
        run: |
          git fetch origin gh-pages || echo "gh-pages branch does not exist"
          git checkout -b gh-pages || git checkout gh-pages
          git reset --hard origin/gh-pages
          cp -r images/* .  # Copy the rendered images to the root directory
          git add .
          git commit -m "Deploy PCB images to gh-pages"
          git push origin gh-pages --force

  deploy-pages-dev:
    if: github.ref == 'refs/heads/dev'  # Only deploy on 'dev' branch
    runs-on: ubuntu-latest
    needs: render-image

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages-dev
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or update gh-pages-dev branch (dev)
        run: |
          git fetch origin gh-pages-dev || echo "gh-pages-dev branch does not exist"
          git checkout -b gh-pages-dev || git checkout gh-pages-dev
          git reset --hard origin/gh-pages-dev
          cp -r images/* .  # Copy the rendered images to the root directory
          git add .
          git commit -m "Deploy PCB images to gh-pages-dev"
          git push origin gh-pages-dev --force
